export const AUDIENCE_ADD_REQUEST = 'AUDIENCE_ADD_REQUEST'
export const AUDIENCE_ADD_SUCCESS = 'AUDIENCE_ADD_SUCCESS'
export const AUDIENCE_ADD_FAIL = 'AUDIENCE_ADD_FAIL'

export const AUDIENCE_UPDATE_REQUEST = 'AUDIENCE_UPDATE_REQUEST'
export const AUDIENCE_UPDATE_SUCCESS = 'AUDIENCE_UPDATE_SUCCESS'
export const AUDIENCE_UPDATE_FAIL = 'AUDIENCE_UPDATE_FAIL'

export const AUDIENCE_DELETE_REQUEST = 'AUDIENCE_DELETE_REQUEST'
export const AUDIENCE_DELETE_SUCCESS = 'AUDIENCE_DELETE_SUCCESS'
export const AUDIENCE_DELETE_FAIL = 'AUDIENCE_DELETE_FAIL'

