export const CARS_ADD_REQUEST = 'CARS_ADD_REQUEST'
export const CARS_ADD_SUCCESS = 'CARS_ADD_SUCCESS'
export const CARS_ADD_FAIL = 'CARS_ADD_FAIL'

export const CARS_UPDATE_REQUEST = 'CARS_UPDATE_REQUEST'
export const CARS_UPDATE_SUCCESS = 'CARS_UPDATE_SUCCESS'
export const CARS_UPDATE_FAIL = 'CARS_UPDATE_FAIL'

export const CARS_DELETE_REQUEST = 'CARS_DELETE_REQUEST'
export const CARS_DELETE_SUCCESS = 'CARS_DELETE_SUCCESS'
export const CARS_DELETE_FAIL = 'CARS_DELETE_FAIL'

