export const DIRECTORY_ADD_REQUEST = 'DIRECTORY_ADD_REQUEST'
export const DIRECTORY_ADD_SUCCESS = 'DIRECTORY_ADD_SUCCESS'
export const DIRECTORY_ADD_FAIL = 'DIRECTORY_ADD_FAIL'

export const DIRECTORY_UPDATE_REQUEST = 'DIRECTORY_UPDATE_REQUEST'
export const DIRECTORY_UPDATE_SUCCESS = 'DIRECTORY_UPDATE_SUCCESS'
export const DIRECTORY_UPDATE_FAIL = 'DIRECTORY_UPDATE_FAIL'

export const DIRECTORY_DELETE_REQUEST = 'DIRECTORY_DELETE_REQUEST'
export const DIRECTORY_DELETE_SUCCESS = 'DIRECTORY_DELETE_SUCCESS'
export const DIRECTORY_DELETE_FAIL = 'DIRECTORY_DELETE_FAIL'

