export const INACTIVE_CANDIDATE_ADD_REQUEST = 'INACTIVE_CANDIDATE_ADD_REQUEST'
export const INACTIVE_CANDIDATE_ADD_SUCCESS = 'INACTIVE_CANDIDATE_ADD_SUCCESS'
export const INACTIVE_CANDIDATE_ADD_FAIL = 'INACTIVE_CANDIDATE_ADD_FAIL'

export const INACTIVE_CANDIDATE_UPDATE_REQUEST = 'INACTIVE_CANDIDATE_UPDATE_REQUEST'
export const INACTIVE_CANDIDATE_UPDATE_SUCCESS = 'INACTIVE_CANDIDATE_UPDATE_SUCCESS'
export const INACTIVE_CANDIDATE_UPDATE_FAIL = 'INACTIVE_CANDIDATE_UPDATE_FAIL'

export const INACTIVE_CANDIDATE_DELETE_REQUEST = 'INACTIVE_CANDIDATE_DELETE_REQUEST'
export const INACTIVE_CANDIDATE_DELETE_SUCCESS = 'INACTIVE_CANDIDATE_DELETE_SUCCESS'
export const INACTIVE_CANDIDATE_DELETE_FAIL = 'INACTIVE_CANDIDATE_DELETE_FAIL'

