export const INACTIVE_CONTRACTS_ADD_REQUEST = 'INACTIVE_CONTRACTS_ADD_REQUEST'
export const INACTIVE_CONTRACTS_ADD_SUCCESS = 'INACTIVE_CONTRACTS_ADD_SUCCESS'
export const INACTIVE_CONTRACTS_ADD_FAIL = 'INACTIVE_CONTRACTS_ADD_FAIL'

export const INACTIVE_CONTRACTS_UPDATE_REQUEST = 'INACTIVE_CONTRACTS_UPDATE_REQUEST'
export const INACTIVE_CONTRACTS_UPDATE_SUCCESS = 'INACTIVE_CONTRACTS_UPDATE_SUCCESS'
export const INACTIVE_CONTRACTS_UPDATE_FAIL = 'INACTIVE_CONTRACTS_UPDATE_FAIL'

export const INACTIVE_CONTRACTS_DELETE_REQUEST = 'INACTIVE_CONTRACTS_DELETE_REQUEST'
export const INACTIVE_CONTRACTS_DELETE_SUCCESS = 'INACTIVE_CONTRACTS_DELETE_SUCCESS'
export const INACTIVE_CONTRACTS_DELETE_FAIL = 'INACTIVE_CONTRACTS_DELETE_FAIL'

