export const ADD_STAFF_REQUEST = 'ADD_STAFF_REQUEST'
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS'
export const ADD_STAFF_FAIL = 'ADD_STAFF_FAIL'

export const STAFF_DELETE_REQUEST = 'STAFF_DELETE_REQUEST'
export const STAFF_DELETE_SUCCESS = 'STAFF_DELETE_SUCCESS'
export const STAFF_DELETE_FAIL = 'STAFF_DELETE_FAIL'

export const STAFF_UPDATE_REQUEST = 'STAFF_UPDATE_REQUEST'
export const STAFF_UPDATE_SUCCESS = 'STAFF_UPDATE_SUCCESS'
export const STAFF_UPDATE_FAIL = 'STAFF_UPDATE_FAIL'

export const ADD_TEST = 'ADD_TEST'
