export const SUBJECT_ADD_REQUEST = 'SUBJECT_ADD_REQUEST'
export const SUBJECT_ADD_SUCCESS = 'SUBJECT_ADD_SUCCESS'
export const SUBJECT_ADD_FAIL = 'SUBJECT_ADD_FAIL'

export const SUBJECT_UPDATE_REQUEST = 'SUBJECT_UPDATE_REQUEST'
export const SUBJECT_UPDATE_SUCCESS = 'SUBJECT_UPDATE_SUCCESS'
export const SUBJECT_UPDATE_FAIL = 'SUBJECT_UPDATE_FAIL'

export const SUBJECT_DELETE_REQUEST = 'SUBJECT_DELETE_REQUEST'
export const SUBJECT_DELETE_SUCCESS = 'SUBJECT_DELETE_SUCCESS'
export const SUBJECT_DELETE_FAIL = 'SUBJECT_DELETE_FAIL'


